/* Resource Datei Indizes fÅr COPYRIGT */

#define MAIN             0   /* Formular/Dialog */
#define MAINBOX          0   /* BOX in Baum MAIN */
#define MAINOK           1   /* BUTTON in Baum MAIN */
#define NAME             3   /* FBOXTEXT in Baum MAIN */
#define STREET           8   /* FBOXTEXT in Baum MAIN */
#define STATE            9   /* FBOXTEXT in Baum MAIN */
#define SERIAL           10  /* FBOXTEXT in Baum MAIN */
#define VERSION          12  /* FBOXTEXT in Baum MAIN */
#define MAINEX           14  /* BUTTON in Baum MAIN */
#define GETSER1          15  /* BUTTON in Baum MAIN */
#define GETSER2          16  /* BUTTON in Baum MAIN */

#define ALERTBOX         1   /* Formular/Dialog */
#define ALERTCOL         0   /* BOX in Baum ALERTBOX */
