/* Resource Datei Indizes fÅr ROBOCLK */

#define ROBOCLK          0   /* Formular/Dialog */
#define WMBOX1           0   /* BOX in Baum ROBOCLK */
#define WMHELP           1   /* BOXTEXT in Baum ROBOCLK */
#define WMEXIT           2   /* BUTTON in Baum ROBOCLK */
#define SYNCALC          4   /* BUTTON in Baum ROBOCLK */
#define WMBOX2           5   /* BOX in Baum ROBOCLK */
#define SYNCSRTE         6   /* FTEXT in Baum ROBOCLK */

#define ALERTBOX         1   /* Formular/Dialog */
#define ALERTCOL         0   /* BOX in Baum ALERTBOX */
