/* Resource Datei Indizes fÅr SAMPLER4 */

#define SMP16            0   /* Formular/Dialog */
#define EXIT             3   /* BUTTON in Baum SMP16 */
#define DATEI            5   /* TEXT in Baum SMP16 */
#define PROT             8   /* BUTTON in Baum SMP16 */
#define EMPH             9   /* BUTTON in Baum SMP16 */
#define AUDIO            10  /* BUTTON in Baum SMP16 */
#define USE              11  /* BUTTON in Baum SMP16 */
#define SMP32            13  /* BUTTON in Baum SMP16 */
#define SMP44            14  /* BUTTON in Baum SMP16 */
#define SMP48            15  /* BUTTON in Baum SMP16 */
#define NOVAL            17  /* BUTTON in Baum SMP16 */
#define CONFID           18  /* BUTTON in Baum SMP16 */
#define SLIPPED          19  /* BUTTON in Baum SMP16 */
#define CRC              20  /* BUTTON in Baum SMP16 */
#define PARITY           21  /* BUTTON in Baum SMP16 */
#define BIPHASE          22  /* BUTTON in Baum SMP16 */
#define NOLOCK           23  /* BUTTON in Baum SMP16 */
#define EDIT             26  /* BUTTON in Baum SMP16 */
#define SWDSP            27  /* BUTTON in Baum SMP16 */
#define PEAKSW           28  /* BUTTON in Baum SMP16 */
#define PROTECT          36  /* BUTTON in Baum SMP16 */
#define INPUT            38  /* BOXTEXT in Baum SMP16 */
#define INCIRC           39  /* BOXCHAR in Baum SMP16 */
#define SOURCE           40  /* BOXTEXT in Baum SMP16 */
#define SRCCIRC          41  /* BOXCHAR in Baum SMP16 */
#define SMPAUTO          43  /* BUTTON in Baum SMP16 */
#define SMPSTART         44  /* BUTTON in Baum SMP16 */
#define PLAY             46  /* BUTTON in Baum SMP16 */
#define RATE2            50  /* BOXTEXT in Baum SMP16 */
#define RATECIR2         51  /* BOXCHAR in Baum SMP16 */
#define HELPORIG         52  /* BOXTEXT in Baum SMP16 */
#define DSP              56  /* BOXTEXT in Baum SMP16 */
#define DSPCIRC          57  /* BOXCHAR in Baum SMP16 */
#define FILESEL          59  /* BUTTON in Baum SMP16 */
#define MEMUSED          61  /* TEXT in Baum SMP16 */

#define SMPEDIT          1   /* Formular/Dialog */
#define SMPSTA           5   /* BUTTON in Baum SMPEDIT */
#define SMPSTB           6   /* BUTTON in Baum SMPEDIT */
#define SMPSTC           7   /* BUTTON in Baum SMPEDIT */
#define SMPSTD           8   /* BUTTON in Baum SMPEDIT */
#define SMPSTE           9   /* BUTTON in Baum SMPEDIT */
#define SMPSAVL          10  /* BUTTON in Baum SMPEDIT */
#define SMPTSA           11  /* BOXTEXT in Baum SMPEDIT */
#define SMPTSB           12  /* BOXTEXT in Baum SMPEDIT */
#define SMPTSC           13  /* BOXTEXT in Baum SMPEDIT */
#define SMPTSD           14  /* BOXTEXT in Baum SMPEDIT */
#define SMPTSE           15  /* BOXTEXT in Baum SMPEDIT */
#define HACKSA           16  /* BOXTEXT in Baum SMPEDIT */
#define HACKSB           17  /* BOXTEXT in Baum SMPEDIT */
#define HACKSC           18  /* BOXTEXT in Baum SMPEDIT */
#define HACKSD           19  /* BOXTEXT in Baum SMPEDIT */
#define SMPEA            22  /* BUTTON in Baum SMPEDIT */
#define SMPEB            23  /* BUTTON in Baum SMPEDIT */
#define SMPEC            24  /* BUTTON in Baum SMPEDIT */
#define SMPED            25  /* BUTTON in Baum SMPEDIT */
#define SMPEE            26  /* BUTTON in Baum SMPEDIT */
#define SMPSAVR          27  /* BUTTON in Baum SMPEDIT */
#define SMPLEN           28  /* BOXTEXT in Baum SMPEDIT */
#define SMPSEC           29  /* BOXTEXT in Baum SMPEDIT */
#define SMPEXIT          33  /* BUTTON in Baum SMPEDIT */
#define SMPL1            35  /* BUTTON in Baum SMPEDIT */
#define SMPR1            36  /* BUTTON in Baum SMPEDIT */
#define SMPL2            37  /* BUTTON in Baum SMPEDIT */
#define SMPR2            38  /* BUTTON in Baum SMPEDIT */
#define SMPL3            39  /* BUTTON in Baum SMPEDIT */
#define SMPR3            40  /* BUTTON in Baum SMPEDIT */
#define SMPANF           41  /* BUTTON in Baum SMPEDIT */
#define SMPEND           42  /* BUTTON in Baum SMPEDIT */
#define SMPMID           43  /* BUTTON in Baum SMPEDIT */
#define RATE             44  /* BOXTEXT in Baum SMPEDIT */
#define RATECIRC         45  /* BOXCHAR in Baum SMPEDIT */
#define SMPTSAVA         46  /* BOXTEXT in Baum SMPEDIT */
#define HACKSE           47  /* BOXTEXT in Baum SMPEDIT */
#define HACKSS           48  /* BOXTEXT in Baum SMPEDIT */
#define SMPLOOP          50  /* USERDEF in Baum SMPEDIT */
#define SMPPMARK         51  /* USERDEF in Baum SMPEDIT */
#define MIDI             53  /* USERDEF in Baum SMPEDIT */
#define MINTEXT          54  /* BOXTEXT in Baum SMPEDIT */
#define SMPFILE          55  /* BOXTEXT in Baum SMPEDIT */
#define SMPRATE          56  /* BOXTEXT in Baum SMPEDIT */
#define MOVER            59  /* BOXTEXT in Baum SMPEDIT */
#define MOVECIRC         60  /* BOXCHAR in Baum SMPEDIT */
#define UHR              61  /* USERDEF in Baum SMPEDIT */
#define SMPTEA           62  /* BOXTEXT in Baum SMPEDIT */
#define SMPTEB           63  /* BOXTEXT in Baum SMPEDIT */
#define SMPTEC           64  /* BOXTEXT in Baum SMPEDIT */
#define SMPTED           65  /* BOXTEXT in Baum SMPEDIT */
#define SMPTEE           66  /* BOXTEXT in Baum SMPEDIT */
#define SMPTSAVB         67  /* BOXTEXT in Baum SMPEDIT */
#define HACKEA           68  /* BOXTEXT in Baum SMPEDIT */
#define HACKEB           69  /* BOXTEXT in Baum SMPEDIT */
#define HACKEC           70  /* BOXTEXT in Baum SMPEDIT */
#define HACKED           71  /* BOXTEXT in Baum SMPEDIT */
#define HACKEE           72  /* BOXTEXT in Baum SMPEDIT */
#define HACKES           73  /* BOXTEXT in Baum SMPEDIT */
#define HELPEDIT         75  /* USERDEF in Baum SMPEDIT */
#define NORM             76  /* USERDEF in Baum SMPEDIT */
#define RESMP            77  /* USERDEF in Baum SMPEDIT */
#define MONO             78  /* USERDEF in Baum SMPEDIT */
#define MIX              79  /* USERDEF in Baum SMPEDIT */
#define EDFADE           80  /* USERDEF in Baum SMPEDIT */
#define PEAKSW2          81  /* USERDEF in Baum SMPEDIT */
#define HEAR             82  /* USERDEF in Baum SMPEDIT */
#define MONITOR          83  /* USERDEF in Baum SMPEDIT */
#define SMPAUTO2         84  /* USERDEF in Baum SMPEDIT */
#define SMPSTRT2         85  /* USERDEF in Baum SMPEDIT */
#define SMPPLAY          86  /* USERDEF in Baum SMPEDIT */
#define EDMIDI           87  /* USERDEF in Baum SMPEDIT */
#define LOOPART          88  /* USERDEF in Baum SMPEDIT */
#define SMPLOAD          89  /* USERDEF in Baum SMPEDIT */
#define SMPSAVE          90  /* USERDEF in Baum SMPEDIT */
#define CUT              91  /* USERDEF in Baum SMPEDIT */
#define HARD             92  /* USERDEF in Baum SMPEDIT */
#define ARRANGE          93  /* USERDEF in Baum SMPEDIT */

#define DSPEDIT          2   /* Formular/Dialog */
#define DSPHALL          2   /* BUTTON in Baum DSPEDIT */
#define DSPECHO          3   /* BUTTON in Baum DSPEDIT */
#define DSPRET           4   /* BUTTON in Baum DSPEDIT */
#define DSPEQ            5   /* BUTTON in Baum DSPEDIT */
#define DSPLOAD          6   /* BUTTON in Baum DSPEDIT */
#define HELPDSP          7   /* BOXTEXT in Baum DSPEDIT */
#define DSPEXIT          8   /* BUTTON in Baum DSPEDIT */
#define DSPSAVE          9   /* BUTTON in Baum DSPEDIT */

#define PEAK             3   /* Formular/Dialog */
#define PLMIN            14  /* BUTTON in Baum PEAK */
#define PL2              15  /* BUTTON in Baum PEAK */
#define PL3              16  /* BUTTON in Baum PEAK */
#define PL4              17  /* BUTTON in Baum PEAK */
#define PL5              18  /* BUTTON in Baum PEAK */
#define PL6              19  /* BUTTON in Baum PEAK */
#define PL7              20  /* BUTTON in Baum PEAK */
#define PL8              21  /* BUTTON in Baum PEAK */
#define PL9              22  /* BUTTON in Baum PEAK */
#define PLMAX            23  /* BUTTON in Baum PEAK */
#define PRMIN            24  /* BUTTON in Baum PEAK */
#define PR2              25  /* BUTTON in Baum PEAK */
#define PR3              26  /* BUTTON in Baum PEAK */
#define PR4              27  /* BUTTON in Baum PEAK */
#define PR5              28  /* BUTTON in Baum PEAK */
#define PR6              29  /* BUTTON in Baum PEAK */
#define PR7              30  /* BUTTON in Baum PEAK */
#define PR8              31  /* BUTTON in Baum PEAK */
#define PR9              32  /* BUTTON in Baum PEAK */
#define PRMAX            33  /* BUTTON in Baum PEAK */

#define LOOP             4   /* Formular/Dialog */
#define LOOPEXIT         1   /* BUTTON in Baum LOOP */
#define FORW             3   /* BUTTON in Baum LOOP */
#define CROSS            4   /* BUTTON in Baum LOOP */
#define BACKW            5   /* BUTTON in Baum LOOP */
#define HELPLOOP         7   /* BOXTEXT in Baum LOOP */
#define AUTOLOOP         8   /* BUTTON in Baum LOOP */

#define NORMALIZ         5   /* Formular/Dialog */
#define NORMOK           2   /* BUTTON in Baum NORMALIZ */
#define NORMEXIT         3   /* BUTTON in Baum NORMALIZ */
#define NORMDB           4   /* BOXTEXT in Baum NORMALIZ */
#define NORMAUTO         7   /* BUTTON in Baum NORMALIZ */
#define NORMADJ          8   /* BUTTON in Baum NORMALIZ */
#define NORML1           10  /* BUTTON in Baum NORMALIZ */
#define NORMR1           11  /* BUTTON in Baum NORMALIZ */
#define NORML2           12  /* BUTTON in Baum NORMALIZ */
#define NORMR2           13  /* BUTTON in Baum NORMALIZ */
#define NORML3           14  /* BUTTON in Baum NORMALIZ */
#define NORMR3           15  /* BUTTON in Baum NORMALIZ */
#define HELPNORM         16  /* BOXTEXT in Baum NORMALIZ */

#define RESAMPLE         6   /* Formular/Dialog */
#define RESOTHER         1   /* BOXTEXT in Baum RESAMPLE */
#define RESL1            3   /* BUTTON in Baum RESAMPLE */
#define RESL2            4   /* BUTTON in Baum RESAMPLE */
#define RESL3            5   /* BUTTON in Baum RESAMPLE */
#define RESR1            6   /* BUTTON in Baum RESAMPLE */
#define RESR2            7   /* BUTTON in Baum RESAMPLE */
#define RESR3            8   /* BUTTON in Baum RESAMPLE */
#define RES32            13  /* BUTTON in Baum RESAMPLE */
#define RES44            15  /* BUTTON in Baum RESAMPLE */
#define RES48            17  /* BUTTON in Baum RESAMPLE */
#define HELPRSMP         18  /* BOXTEXT in Baum RESAMPLE */
#define RESTXT           19  /* BOXTEXT in Baum RESAMPLE */
#define RESOK            20  /* BUTTON in Baum RESAMPLE */
#define RESEXIT          21  /* BUTTON in Baum RESAMPLE */

#define MIDIEDIT         7   /* Formular/Dialog */
#define NOTETXT          1   /* BOXTEXT in Baum MIDIEDIT */
#define MIDINUP          2   /* BUTTON in Baum MIDIEDIT */
#define MIDINDWN         3   /* BUTTON in Baum MIDIEDIT */
#define MIDIOUP          4   /* BUTTON in Baum MIDIEDIT */
#define MIDIODWN         5   /* BUTTON in Baum MIDIEDIT */
#define CHTXT            7   /* BOXTEXT in Baum MIDIEDIT */
#define MIDICUP          9   /* BUTTON in Baum MIDIEDIT */
#define MIDICDWN         10  /* BUTTON in Baum MIDIEDIT */
#define MIDIOK           11  /* BUTTON in Baum MIDIEDIT */
#define HELPMIDI         13  /* BOXTEXT in Baum MIDIEDIT */

#define EDITFADE         8   /* Formular/Dialog */
#define FADEOK           2   /* BUTTON in Baum EDITFADE */
#define FADEUP           3   /* BUTTON in Baum EDITFADE */
#define FADEDOWN         4   /* BUTTON in Baum EDITFADE */
#define FADELI           5   /* BUTTON in Baum EDITFADE */
#define FADERE           6   /* BUTTON in Baum EDITFADE */
#define FADELIN          8   /* BUTTON in Baum EDITFADE */
#define INFADE           10  /* BUTTON in Baum EDITFADE */
#define AUSFADE          11  /* BUTTON in Baum EDITFADE */
#define HELPFADE         12  /* BOXTEXT in Baum EDITFADE */

#define POPUPS           9   /* Formular/Dialog */
#define SMPPOPUP         1   /* BOX in Baum POPUPS */
#define RATE32           2   /* STRING in Baum POPUPS */
#define RATE44           3   /* STRING in Baum POPUPS */
#define RATE48           4   /* STRING in Baum POPUPS */
#define DSPPOPUP         5   /* BOX in Baum POPUPS */
#define DSPOFF           6   /* STRING in Baum POPUPS */
#define DSPIN            7   /* STRING in Baum POPUPS */
#define DSPOUT           8   /* STRING in Baum POPUPS */
#define SMPPOP2          9   /* BOX in Baum POPUPS */
#define AD32             10  /* STRING in Baum POPUPS */
#define AD44             11  /* STRING in Baum POPUPS */
#define AD48             12  /* STRING in Baum POPUPS */
#define INPOP            13  /* BOX in Baum POPUPS */
#define ANALOG           14  /* STRING in Baum POPUPS */
#define DIGITAL          15  /* STRING in Baum POPUPS */
#define SRCPOP           16  /* BOX in Baum POPUPS */
#define OPTO             17  /* STRING in Baum POPUPS */
#define COAX             18  /* STRING in Baum POPUPS */
#define POPMARK          19  /* BOX in Baum POPUPS */
#define SMPMARK          20  /* STRING in Baum POPUPS */
#define SMPZOOM          21  /* STRING in Baum POPUPS */
#define SMPSCROL         22  /* STRING in Baum POPUPS */
#define KOPY             23  /* STRING in Baum POPUPS */
#define MOVE             24  /* STRING in Baum POPUPS */
#define MERGE            25  /* STRING in Baum POPUPS */
#define FADE             26  /* STRING in Baum POPUPS */

#define RECORD           10  /* Formular/Dialog */
#define RECL1            1   /* BUTTON in Baum RECORD */
#define RECR1            2   /* BUTTON in Baum RECORD */
#define RECL2            3   /* BUTTON in Baum RECORD */
#define RECR2            4   /* BUTTON in Baum RECORD */
#define TIMETXT          5   /* BOXTEXT in Baum RECORD */
#define RECOK            6   /* BUTTON in Baum RECORD */
#define RECEXIT          7   /* BUTTON in Baum RECORD */

#define CUTEDIT          11  /* Formular/Dialog */
#define CUTIN            1   /* USERDEF in Baum CUTEDIT */
#define CUTOUT           2   /* USERDEF in Baum CUTEDIT */
#define CUTEXIT          3   /* BUTTON in Baum CUTEDIT */

#define SAVEBLOC         12  /* Formular/Dialog */
#define SAVALL           1   /* USERDEF in Baum SAVEBLOC */
#define SAVBLOCK         2   /* USERDEF in Baum SAVEBLOC */
#define SAVEXIT          3   /* BUTTON in Baum SAVEBLOC */

#define ARRANGER         13  /* Formular/Dialog */
#define HLPEDIT2         2   /* USERDEF in Baum ARRANGER */
#define SMPLOAD2         3   /* USERDEF in Baum ARRANGER */
#define SMPSAVE2         4   /* USERDEF in Baum ARRANGER */
#define HARDCUT          5   /* USERDEF in Baum ARRANGER */
#define SMPAUTO3         7   /* USERDEF in Baum ARRANGER */
#define SMPSTRT3         8   /* USERDEF in Baum ARRANGER */
#define SMPPLAY2         9   /* USERDEF in Baum ARRANGER */
#define PAUSE            10  /* USERDEF in Baum ARRANGER */
#define REWIND           11  /* USERDEF in Baum ARRANGER */
#define STOP             12  /* USERDEF in Baum ARRANGER */
#define FORWARD          13  /* USERDEF in Baum ARRANGER */
#define RECPLAY          14  /* USERDEF in Baum ARRANGER */
#define HARDFS1          25  /* BUTTON in Baum ARRANGER */
#define HARDFS2          27  /* BUTTON in Baum ARRANGER */
#define HARDFS3          29  /* BUTTON in Baum ARRANGER */
#define HARDFS4          31  /* BUTTON in Baum ARRANGER */
#define HARDST1          33  /* TEXT in Baum ARRANGER */
#define HARDST2          35  /* TEXT in Baum ARRANGER */
#define HARDST3          37  /* TEXT in Baum ARRANGER */
#define HARDST4          39  /* TEXT in Baum ARRANGER */
#define HARDE2           41  /* TEXT in Baum ARRANGER */
#define HARDE3           43  /* TEXT in Baum ARRANGER */
#define HARDE4           45  /* TEXT in Baum ARRANGER */
#define HARDE1           49  /* TEXT in Baum ARRANGER */
#define HARDLEN1         51  /* TEXT in Baum ARRANGER */
#define HARDLEN2         53  /* TEXT in Baum ARRANGER */
#define HARDLEN3         55  /* TEXT in Baum ARRANGER */
#define HARDLEN4         57  /* TEXT in Baum ARRANGER */
#define ARREXIT          65  /* BUTTON in Baum ARRANGER */
