/* Resource Datei Indizes fÅr INSTALL */

#define MAIN             0   /* Formular/Dialog */
#define MAINBOX          0   /* BOX in Baum MAIN */
#define MAINOK           1   /* BUTTON in Baum MAIN */
#define MEMORY           4   /* FBOXTEXT in Baum MAIN */
#define PATHTEX          5   /* STRING in Baum MAIN */
#define PATHAUTO         6   /* BOXTEXT in Baum MAIN */
#define SPKBRD           7   /* BUTTON in Baum MAIN */
#define SPKGBR           8   /* BUTTON in Baum MAIN */
#define SPKFR            9   /* BUTTON in Baum MAIN */
#define PATHPROG         11  /* BOXTEXT in Baum MAIN */
#define HELPINST         13  /* BUTTON in Baum MAIN */
#define HELPTEX          15  /* STRING in Baum MAIN */
#define MAINEX           19  /* BUTTON in Baum MAIN */
#define INFTEXT          20  /* BOXTEXT in Baum MAIN */

#define INFO             1   /* Formular/Dialog */
#define INFOBOX          0   /* BOX in Baum INFO */
#define INFOEX           2   /* BUTTON in Baum INFO */

#define INFO2            2   /* Formular/Dialog */
#define INFOBOX2         0   /* BOX in Baum INFO2 */
#define INFOEX2          2   /* BUTTON in Baum INFO2 */

#define ALERTBOX         3   /* Formular/Dialog */
#define ALERTCOL         0   /* BOX in Baum ALERTBOX */
